/**
 * SLA Breach Detection Cron
 * ─────────────────────────────────────────────────────────────────────────────
 * Runs every 15 minutes. Detects work orders that have breached their SLA
 * (not completed within priority-based time window) and sends notifications.
 */

import { NextResponse } from "next/server"
import { serviceDb } from "@/lib/db"
import { sql } from "drizzle-orm"
import { notifications } from "@/lib/db/schema"
import { logger } from "@/lib/logger"

export const runtime = "nodejs"
export const maxDuration = 30

const SLA_HOURS: Record<string, number> = { critical: 4, high: 8, medium: 24, low: 72 }

export async function GET(request: Request) {
  const authHeader = request.headers.get("authorization")
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    let breached = 0

    // Find open/assigned/in_progress work orders that have breached SLA
    for (const [priority, hours] of Object.entries(SLA_HOURS)) {
      const breachedWOs = await serviceDb.execute<{
        id: string
        work_order_number: string
        title: string
        property_id: string
        assigned_to: string | null
        created_at: string
      }>(sql`
        SELECT wo.id, wo.work_order_number, wo.title, wo.property_id, wo.assigned_to, wo.created_at
        FROM work_orders wo
        WHERE wo.priority = ${priority}
          AND wo.status IN ('open', 'assigned', 'in_progress')
          AND wo.created_at < NOW() - INTERVAL '${sql.raw(String(hours))} hours'
          AND NOT EXISTS (
            SELECT 1 FROM notifications n
            WHERE n.type = 'sla_breach'
              AND (n.metadata->>'workOrderId') = wo.id::text
          )
      `)

      for (const wo of breachedWOs) {
        // Get property managers to notify
        const managers = await serviceDb.execute<{ id: string }>(sql`
          SELECT DISTINCT u.id FROM users u
          JOIN properties p ON p.organization_id = u.organization_id
          WHERE p.id = ${wo.property_id}::uuid
            AND u.status = 'active'
            AND (u.properties::jsonb @> ${JSON.stringify([wo.property_id])}::jsonb
                 OR EXISTS (SELECT 1 FROM roles r WHERE r.id = u.role_id AND r.name IN ('super_admin', 'organization_admin', 'property_manager')))
          LIMIT 5
        `)

        for (const manager of managers) {
          await serviceDb.insert(notifications).values({
            recipientId: manager.id,
            recipientType: "user",
            type: "sla_breach",
            channel: "in_app",
            title: `SLA Breached: ${wo.work_order_number}`,
            content: `Work order "${wo.title}" (${priority} priority) has exceeded the ${hours}-hour SLA. Immediate attention required.`,
            status: "sent",
            sentAt: new Date(),
            autoGenerated: true,
            metadata: { workOrderId: wo.id, priority, slaHours: hours },
          }).catch(() => {})
        }

        // Escalate to critical if not already
        if (priority !== "critical") {
          await serviceDb.execute(sql`
            UPDATE work_orders SET
              metadata = jsonb_set(COALESCE(metadata, '{}'), '{slaBreached}', 'true'),
              updated_at = NOW()
            WHERE id = ${wo.id}::uuid
          `)
        }

        breached++
      }
    }

    logger.info("sla-breach: completed", { breached })
    return NextResponse.json({ success: true, breached })
  } catch (err) {
    logger.error("sla-breach: failed", { error: err })
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
