// ── Notification Dispatcher ──────────────────────────────────────────────────
// Orchestrates: fetch template → render → send via channel → log notification.

import { db } from "@/lib/db"
import { notificationTemplates, notifications } from "@/lib/db/schema"
import { eq, and } from "drizzle-orm"
import { renderTemplate } from "./render"
import { sendEmail } from "./email"
import { sendWhatsApp } from "./whatsapp"
import { sendSMS } from "./sms"
import type { EventType, Channel } from "./variables"

interface DispatchParams {
  eventType: EventType
  organizationId: string
  recipientId: string
  recipientType: "user" | "tenant"
  recipientEmail?: string
  recipientPhone?: string
  data: Record<string, string>
}

interface DispatchResult {
  sent: number
  failed: number
  results: { channel: string; success: boolean; error?: string }[]
}

/**
 * Dispatch notifications for an event.
 * Fetches all active templates matching the event type + org,
 * renders each, sends via the appropriate channel, and logs to notifications table.
 */
export async function dispatchNotification(
  params: DispatchParams
): Promise<DispatchResult> {
  const templates = await db
    .select()
    .from(notificationTemplates)
    .where(
      and(
        eq(notificationTemplates.organizationId, params.organizationId),
        eq(notificationTemplates.eventType, params.eventType),
        eq(notificationTemplates.isActive, true)
      )
    )

  const results: DispatchResult["results"] = []

  for (const tpl of templates) {
    const renderedBody = renderTemplate(tpl.body, params.data)
    const renderedSubject = tpl.subject
      ? renderTemplate(tpl.subject, params.data)
      : undefined

    let sendResult: { success: boolean; messageId?: string; error?: string }

    switch (tpl.channel as Channel) {
      case "email":
        if (!params.recipientEmail) {
          results.push({ channel: "email", success: false, error: "No email address" })
          continue
        }
        sendResult = await sendEmail(
          params.recipientEmail,
          renderedSubject || "Notification",
          renderedBody
        )
        break

      case "whatsapp":
        if (!params.recipientPhone) {
          results.push({ channel: "whatsapp", success: false, error: "No phone number" })
          continue
        }
        sendResult = await sendWhatsApp(params.recipientPhone, renderedBody)
        break

      case "sms":
        if (!params.recipientPhone) {
          results.push({ channel: "sms", success: false, error: "No phone number" })
          continue
        }
        sendResult = await sendSMS(params.recipientPhone, renderedBody)
        break

      default:
        results.push({ channel: tpl.channel, success: false, error: "Unknown channel" })
        continue
    }

    // Log notification record
    await db.insert(notifications).values({
      recipientId: params.recipientId,
      recipientType: params.recipientType,
      type: params.eventType,
      channel: tpl.channel,
      title: renderedSubject || tpl.name,
      content: renderedBody,
      status: sendResult.success ? "sent" : "failed",
      sentAt: sendResult.success ? new Date() : undefined,
      autoGenerated: true,
      metadata: {
        templateId: tpl.id,
        templateName: tpl.name,
        messageId: sendResult.messageId,
        error: sendResult.error,
      },
    })

    results.push({
      channel: tpl.channel,
      success: sendResult.success,
      error: sendResult.error,
    })
  }

  return {
    sent: results.filter((r) => r.success).length,
    failed: results.filter((r) => !r.success).length,
    results,
  }
}

// ── Convenience triggers ─────────────────────────────────────────────────────

export async function onInvoiceCreated(params: {
  organizationId: string
  tenantId: string
  tenantEmail?: string
  tenantPhone?: string
  data: Record<string, string>
}) {
  return dispatchNotification({
    eventType: "invoice_created",
    organizationId: params.organizationId,
    recipientId: params.tenantId,
    recipientType: "tenant",
    recipientEmail: params.tenantEmail,
    recipientPhone: params.tenantPhone,
    data: params.data,
  })
}

export async function onPaymentDue(params: {
  organizationId: string
  tenantId: string
  tenantEmail?: string
  tenantPhone?: string
  data: Record<string, string>
}) {
  return dispatchNotification({
    eventType: "payment_due",
    organizationId: params.organizationId,
    recipientId: params.tenantId,
    recipientType: "tenant",
    recipientEmail: params.tenantEmail,
    recipientPhone: params.tenantPhone,
    data: params.data,
  })
}

export async function onLeaseExpiring(params: {
  organizationId: string
  tenantId: string
  tenantEmail?: string
  tenantPhone?: string
  data: Record<string, string>
}) {
  return dispatchNotification({
    eventType: "lease_expiry",
    organizationId: params.organizationId,
    recipientId: params.tenantId,
    recipientType: "tenant",
    recipientEmail: params.tenantEmail,
    recipientPhone: params.tenantPhone,
    data: params.data,
  })
}

export async function onWorkOrderUpdated(params: {
  organizationId: string
  tenantId: string
  tenantEmail?: string
  tenantPhone?: string
  data: Record<string, string>
}) {
  return dispatchNotification({
    eventType: "work_order_update",
    organizationId: params.organizationId,
    recipientId: params.tenantId,
    recipientType: "tenant",
    recipientEmail: params.tenantEmail,
    recipientPhone: params.tenantPhone,
    data: params.data,
  })
}

export async function onWorkOrderCreated(params: {
  organizationId: string
  tenantId: string
  tenantEmail?: string
  tenantPhone?: string
  data: Record<string, string>
}) {
  return dispatchNotification({
    eventType: "work_order_update",
    organizationId: params.organizationId,
    recipientId: params.tenantId,
    recipientType: "tenant",
    recipientEmail: params.tenantEmail,
    recipientPhone: params.tenantPhone,
    data: params.data,
  })
}

/**
 * Send a direct email (not template-based) — e.g. to a vendor.
 * Used for vendor assignment notifications where there's no tenant template.
 */
export async function sendDirectEmail(
  to: string,
  subject: string,
  html: string
) {
  const { sendEmail } = await import("./email")
  return sendEmail(to, subject, html)
}

export async function onCAMGenerated(params: {
  organizationId: string
  tenantId: string
  tenantEmail?: string
  tenantPhone?: string
  data: Record<string, string>
}) {
  return dispatchNotification({
    eventType: "cam_generated",
    organizationId: params.organizationId,
    recipientId: params.tenantId,
    recipientType: "tenant",
    recipientEmail: params.tenantEmail,
    recipientPhone: params.tenantPhone,
    data: params.data,
  })
}
