/**
 * Lease Expiry Notification Cron
 * ─────────────────────────────────────────────────────────────────────────────
 * Runs daily. Sends notifications at 90, 60, and 30 days before lease expiry.
 */

import { NextResponse } from "next/server"
import { serviceDb } from "@/lib/db"
import { sql } from "drizzle-orm"
import { notifications } from "@/lib/db/schema"
import { onLeaseExpiring } from "@/lib/notifications/dispatcher"
import { logger } from "@/lib/logger"

export const runtime = "nodejs"
export const maxDuration = 60

export async function GET(request: Request) {
  const authHeader = request.headers.get("authorization")
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const today = new Date().toISOString().slice(0, 10)
    const thresholds = [90, 60, 30]
    let totalNotified = 0

    for (const days of thresholds) {
      const targetDate = new Date()
      targetDate.setDate(targetDate.getDate() + days)
      const target = targetDate.toISOString().slice(0, 10)

      // Find leases expiring on this exact date that haven't been notified for this threshold
      const expiringLeases = await serviceDb.execute<{
        lease_id: string
        tenant_id: string
        organization_id: string
        tenant_name: string
        tenant_email: string
        tenant_phone: string
        unit_number: string
        end_date: string
        property_name: string
      }>(sql`
        SELECT
          l.id as lease_id,
          l.tenant_id,
          t.business_name as tenant_name,
          t.email as tenant_email,
          t.phone as tenant_phone,
          l.unit_number,
          l.end_date,
          p.name as property_name,
          p.organization_id
        FROM leases l
        JOIN tenants t ON l.tenant_id = t.id
        JOIN properties p ON l.property_id = p.id
        WHERE l.status = 'active'
          AND l.end_date = ${target}::date
          AND NOT EXISTS (
            SELECT 1 FROM notifications n
            WHERE n.recipient_id = l.tenant_id
              AND n.type = 'lease_expiry'
              AND (n.metadata->>'daysRemaining')::int = ${days}
              AND (n.metadata->>'leaseId') = l.id::text
          )
      `)

      for (const lease of expiringLeases) {
        try {
          // In-app notification
          await serviceDb.insert(notifications).values({
            recipientId: lease.tenant_id,
            recipientType: "tenant",
            type: "lease_expiry",
            channel: "in_app",
            title: `Lease Expiring in ${days} Days`,
            content: `Your lease for unit ${lease.unit_number} at ${lease.property_name} expires on ${lease.end_date}. Please contact property management for renewal.`,
            status: "sent",
            sentAt: new Date(),
            autoGenerated: true,
            metadata: { leaseId: lease.lease_id, daysRemaining: days },
          })

          // Dispatch email/SMS via templates
          if (lease.organization_id) {
            await onLeaseExpiring({
              organizationId: lease.organization_id,
              tenantId: lease.tenant_id,
              tenantEmail: lease.tenant_email ?? undefined,
              tenantPhone: lease.tenant_phone ?? undefined,
              data: {
                tenant_name: lease.tenant_name,
                unit_number: lease.unit_number,
                expiry_date: lease.end_date,
                days_remaining: String(days),
                property_name: lease.property_name,
              },
            }).catch(() => {})
          }

          totalNotified++
        } catch (err) {
          logger.error("lease-expiry: notification failed", { leaseId: lease.lease_id, error: err })
        }
      }
    }

    logger.info("lease-expiry: completed", { totalNotified })
    return NextResponse.json({ success: true, notified: totalNotified })
  } catch (err) {
    logger.error("lease-expiry: cron failed", { error: err })
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
