import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { db, serviceDb } from "@/lib/db"
import { workOrders, tenants, vendors, notifications } from "@/lib/db/schema"
import { eq } from "drizzle-orm"
import { invalidateEntityCache } from "@/lib/cache"
import { onWorkOrderUpdated, sendDirectEmail } from "@/lib/notifications/dispatcher"

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await auth()
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const workOrder = await db.query.workOrders.findFirst({
      where: eq(workOrders.id, params.id),
    })

    if (!workOrder) {
      return NextResponse.json({ error: "Work order not found" }, { status: 404 })
    }

    // Get tenant info if available
    let tenant = null
    if (workOrder.tenantId) {
      tenant = await db.query.tenants.findFirst({
        where: eq(tenants.id, workOrder.tenantId),
      })
    }

    return NextResponse.json({
      ...workOrder,
      tenant: tenant ? {
        id: tenant.id,
        businessName: tenant.businessName,
        contactPerson: tenant.contactPerson,
      } : null,
    })
  } catch (error) {
    console.error("Get work order error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await auth()
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await request.json()
    const { status, priority, assignedTo, notes, resolution } = body

    // Check if work order exists
    const existingWorkOrder = await db.query.workOrders.findFirst({
      where: eq(workOrders.id, params.id),
    })

    if (!existingWorkOrder) {
      return NextResponse.json({ error: "Work order not found" }, { status: 404 })
    }

    // Build update object
    const updateData: Record<string, any> = { updatedAt: new Date() }
    
    if (status !== undefined) {
      updateData.status = status
      // If marking as resolved, set resolved timestamp
      if (status === "resolved") {
        updateData.resolvedAt = new Date()
        updateData.resolvedBy = session.user.id
      }
    }
    
    if (priority !== undefined) updateData.priority = priority
    if (assignedTo !== undefined) {
      updateData.assignedTo = assignedTo
      // If assigning for the first time, set assigned timestamp
      if (!existingWorkOrder.assignedTo && assignedTo) {
        updateData.assignedAt = new Date()
      }
    }
    if (notes !== undefined) updateData.notes = notes
    if (resolution !== undefined) updateData.resolutionNotes = resolution

    const [updatedWorkOrder] = await db
      .update(workOrders)
      .set(updateData)
      .where(eq(workOrders.id, params.id))
      .returning()

    // Invalidate cache
    if (existingWorkOrder.propertyId) {
      await invalidateEntityCache("workorder", params.id, existingWorkOrder.propertyId)
    }

    // Notify tenant + vendor if status/assignment changed (fire-and-forget)
    ;(async () => {
      try {
        const statusMessages: Record<string, string> = {
          assigned: "A technician has been assigned to your request.",
          in_progress: "Work has started on your support request.",
          completed: "Your support request has been completed.",
          resolved: "Your support request has been resolved.",
          cancelled: "Your support request has been cancelled.",
        }

        // In-app + email notification to tenant on status change
        if (status !== undefined && status !== existingWorkOrder.status && updatedWorkOrder.tenantId) {
          const content = statusMessages[status as string]
          if (content) {
            await serviceDb.insert(notifications).values({
              recipientId: updatedWorkOrder.tenantId,
              recipientType: "tenant",
              type: "maintenance_update",
              channel: "in_app",
              title: `Work Order ${updatedWorkOrder.workOrderNumber} – ${String(status).replace(/_/g, " ")}`,
              content,
              status: "sent",
              sentAt: new Date(),
              autoGenerated: true,
              metadata: { workOrderId: params.id, newStatus: status, updatedBy: session.user.id },
            })

            // Email tenant via template dispatcher
            const tenant = await db.query.tenants.findFirst({ where: eq(tenants.id, updatedWorkOrder.tenantId) })
            if (tenant?.email && session.user.organizationId) {
              await onWorkOrderUpdated({
                organizationId: session.user.organizationId,
                tenantId: updatedWorkOrder.tenantId,
                tenantEmail: tenant.email,
                data: {
                  tenant_name: tenant.businessName,
                  work_order_number: updatedWorkOrder.workOrderNumber ?? "",
                  work_order_title: updatedWorkOrder.title,
                  work_order_status: String(status).replace(/_/g, " "),
                  update_message: content,
                },
              })
            }
          }
        }

        // Email vendor when newly assigned
        if (assignedTo !== undefined && assignedTo !== existingWorkOrder.assignedTo && assignedTo) {
          const vendor = await db.query.vendors.findFirst({ where: eq(vendors.id, assignedTo) })
          if (vendor?.email) {
            await sendDirectEmail(
              vendor.email,
              `Work Order Assigned: ${updatedWorkOrder.workOrderNumber}`,
              `<div style="font-family:sans-serif;max-width:600px;margin:0 auto">
                <h2 style="color:#1a1a2e">Work Order Assigned — ${updatedWorkOrder.workOrderNumber}</h2>
                <p>Dear ${vendor.name},</p>
                <p>You have been assigned a new work order. Please review the details below:</p>
                <table style="width:100%;border-collapse:collapse;margin:16px 0">
                  <tr><td style="padding:8px;font-weight:bold;background:#f5f5f5">Title</td><td style="padding:8px">${updatedWorkOrder.title}</td></tr>
                  <tr><td style="padding:8px;font-weight:bold;background:#f5f5f5">Priority</td><td style="padding:8px;text-transform:capitalize">${updatedWorkOrder.priority ?? "medium"}</td></tr>
                  <tr><td style="padding:8px;font-weight:bold;background:#f5f5f5">Location</td><td style="padding:8px">${updatedWorkOrder.location ?? "—"}</td></tr>
                  <tr><td style="padding:8px;font-weight:bold;background:#f5f5f5">Description</td><td style="padding:8px">${updatedWorkOrder.description ?? "—"}</td></tr>
                </table>
                <p>Please log in to the portal to acknowledge and update the work order status.</p>
                <p style="color:#666;font-size:12px;margin-top:32px">MallOS — Metro Properties Group</p>
              </div>`
            )
          }
        }
      } catch {}
    })()

    return NextResponse.json(updatedWorkOrder)
  } catch (error) {
    console.error("Update work order error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const session = await auth()
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // Soft delete by setting status to cancelled
    const [deletedWorkOrder] = await db
      .update(workOrders)
      .set({ 
        status: "cancelled", 
        updatedAt: new Date(),
      })
      .where(eq(workOrders.id, params.id))
      .returning()

    if (!deletedWorkOrder) {
      return NextResponse.json({ error: "Work order not found" }, { status: 404 })
    }

    // Invalidate cache
    if (deletedWorkOrder.propertyId) {
      await invalidateEntityCache("workorder", params.id, deletedWorkOrder.propertyId)
    }

    return NextResponse.json({ message: "Work order cancelled successfully" })
  } catch (error) {
    console.error("Delete work order error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

