/**
 * Compliance Reminder Cron
 * ─────────────────────────────────────────────────────────────────────────────
 * Runs daily. Checks compliance requirements with auto_reminder = true
 * and sends notifications at configured reminder_days thresholds.
 * Also marks overdue items.
 */

import { NextResponse } from "next/server"
import { serviceDb } from "@/lib/db"
import { sql } from "drizzle-orm"
import { notifications } from "@/lib/db/schema"
import { logger } from "@/lib/logger"

export const runtime = "nodejs"
export const maxDuration = 60

export async function GET(request: Request) {
  const authHeader = request.headers.get("authorization")
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const today = new Date().toISOString().slice(0, 10)
    let reminders = 0
    let overdue = 0

    // Mark overdue items
    const markedOverdue = await serviceDb.execute(sql`
      UPDATE compliance_requirements SET
        status = 'overdue',
        updated_at = NOW()
      WHERE status IN ('pending', 'in_progress')
        AND next_due_date IS NOT NULL
        AND next_due_date < ${today}::date
    `)
    overdue = Number((markedOverdue as unknown as { rowCount?: number })?.rowCount ?? 0)

    // Find requirements due within configured reminder days
    const dueSoon = await serviceDb.execute<{
      id: string
      title: string
      property_id: string
      next_due_date: string
      risk_level: string
      reminder_days: number[]
      organization_id: string
    }>(sql`
      SELECT
        cr.id, cr.title, cr.property_id, cr.next_due_date,
        cr.risk_level, cr.reminder_days,
        p.organization_id
      FROM compliance_requirements cr
      JOIN properties p ON cr.property_id = p.id
      WHERE cr.auto_reminder = true
        AND cr.status IN ('pending', 'in_progress')
        AND cr.next_due_date IS NOT NULL
        AND cr.next_due_date > ${today}::date
        AND cr.next_due_date <= (${today}::date + INTERVAL '90 days')::date
    `)

    for (const req of dueSoon) {
      const daysUntil = Math.ceil((new Date(req.next_due_date).getTime() - new Date(today).getTime()) / 86400000)
      const reminderDays = (req.reminder_days ?? [30, 15, 7, 2]) as number[]

      if (!reminderDays.includes(daysUntil)) continue

      // Check if already sent for this threshold
      const existing = await serviceDb.execute<{ id: string }>(sql`
        SELECT id FROM notifications
        WHERE type = 'compliance_reminder'
          AND (metadata->>'complianceId') = ${req.id}
          AND (metadata->>'daysRemaining')::int = ${daysUntil}
        LIMIT 1
      `)

      if (existing.length > 0) continue

      // Get property managers (users with property access)
      const managers = await serviceDb.execute<{ id: string }>(sql`
        SELECT u.id FROM users u
        WHERE u.organization_id = ${req.organization_id}::uuid
          AND u.status = 'active'
          AND (u.properties::jsonb @> ${JSON.stringify([req.property_id])}::jsonb
               OR EXISTS (SELECT 1 FROM roles r WHERE r.id = u.role_id AND r.name IN ('super_admin', 'organization_admin')))
        LIMIT 5
      `)

      for (const manager of managers) {
        await serviceDb.insert(notifications).values({
          recipientId: manager.id,
          recipientType: "user",
          type: "compliance_reminder",
          channel: "in_app",
          title: `Compliance Due in ${daysUntil} Days: ${req.title}`,
          content: `"${req.title}" is due on ${req.next_due_date}. Risk level: ${req.risk_level}.`,
          status: "sent",
          sentAt: new Date(),
          autoGenerated: true,
          metadata: { complianceId: req.id, daysRemaining: daysUntil, riskLevel: req.risk_level },
        }).catch(() => {})
      }

      reminders++
    }

    logger.info("compliance-reminders: completed", { reminders, overdue })
    return NextResponse.json({ success: true, reminders, overdue })
  } catch (err) {
    logger.error("compliance-reminders: failed", { error: err })
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
