/**
 * Post-Approval Action Executor
 * ─────────────────────────────────────────────────────────────────────────────
 * Dispatches approved agent actions to the appropriate service handler.
 * Each action type maps to a concrete function that performs the operation.
 */

import { serviceDb } from "@/lib/db"
import { workOrders, invoices, notifications, vendors } from "@/lib/db/schema"
import { eq, sql } from "drizzle-orm"
import { logger } from "@/lib/logger"

export type AgentActionRow = {
  id: string
  agentId: string | null
  actionType: string
  entityType: string | null
  entityId: string | null
  inputData: unknown
  metadata: unknown
  [key: string]: unknown
}

type ExecutionResult = Record<string, unknown>

/**
 * Execute an approved agent action by dispatching to the correct handler.
 * Throws on failure (caller is expected to mark the action as failed).
 */
export async function executeApprovedAction(action: AgentActionRow): Promise<ExecutionResult> {
  const handler = ACTION_HANDLERS[action.actionType]

  if (!handler) {
    logger.warn("agent-executor: no handler for action type", { actionType: action.actionType, actionId: action.id })
    return { skipped: true, reason: `No handler for action type: ${action.actionType}` }
  }

  logger.info("agent-executor: executing action", { actionId: action.id, actionType: action.actionType })

  const result = await handler(action)

  logger.info("agent-executor: action executed", { actionId: action.id, result })
  return result
}

// ── Action Handlers ──────────────────────────────────────────────────────────

const ACTION_HANDLERS: Record<string, (action: AgentActionRow) => Promise<ExecutionResult>> = {
  create_work_order: async (action) => {
    const input = action.inputData as Record<string, unknown>
    if (!input?.propertyId || !input?.title) {
      throw new Error("Missing required fields: propertyId, title")
    }

    const woNumber = `WO-${Date.now().toString(36).toUpperCase()}`
    const [created] = await serviceDb
      .insert(workOrders)
      .values({
        propertyId: input.propertyId as string,
        title: input.title as string,
        description: input.description as string || undefined,
        priority: (input.priority as string) || "medium",
        category: input.category as string || undefined,
        location: input.location as string || undefined,
        workOrderNumber: woNumber,
        autoCreated: true,
        predictive: (input.predictive as boolean) || false,
        status: "open",
      })
      .returning({ id: workOrders.id })

    return { created: true, workOrderId: created.id, workOrderNumber: woNumber }
  },

  send_reminder: async (action) => {
    const input = action.inputData as Record<string, unknown>
    if (!input?.recipientId || !input?.content) {
      throw new Error("Missing required fields: recipientId, content")
    }

    const [notif] = await serviceDb
      .insert(notifications)
      .values({
        recipientId: input.recipientId as string,
        recipientType: (input.recipientType as string) || "tenant",
        type: "payment_reminder",
        channel: "in_app",
        title: (input.title as string) || "Payment Reminder",
        content: input.content as string,
        autoGenerated: true,
        status: "sent",
        sentAt: new Date(),
      })
      .returning({ id: notifications.id })

    return { sent: true, notificationId: notif.id }
  },

  update_invoice_status: async (action) => {
    const input = action.inputData as Record<string, unknown>
    if (!action.entityId || !input?.status) {
      throw new Error("Missing entityId or status")
    }

    await serviceDb
      .update(invoices)
      .set({
        status: input.status as string,
        updatedAt: new Date(),
        updatedBy: action.agentId,
      })
      .where(eq(invoices.id, action.entityId))

    return { updated: true, invoiceId: action.entityId, newStatus: input.status }
  },

  escalate_work_order: async (action) => {
    if (!action.entityId) {
      throw new Error("Missing entityId for work order escalation")
    }

    await serviceDb
      .update(workOrders)
      .set({
        priority: "critical",
        updatedAt: new Date(),
        metadata: sql`jsonb_set(COALESCE(metadata, '{}'), '{escalated}', 'true')`,
      })
      .where(eq(workOrders.id, action.entityId))

    return { escalated: true, workOrderId: action.entityId }
  },

  schedule_maintenance: async (action) => {
    const input = action.inputData as Record<string, unknown>
    if (!input?.propertyId || !input?.equipmentId) {
      throw new Error("Missing required fields: propertyId, equipmentId")
    }

    const woNumber = `PM-${Date.now().toString(36).toUpperCase()}`
    const [created] = await serviceDb
      .insert(workOrders)
      .values({
        propertyId: input.propertyId as string,
        equipmentId: input.equipmentId as string,
        title: (input.title as string) || "Scheduled Maintenance",
        description: input.description as string || undefined,
        type: "maintenance",
        priority: "medium",
        workOrderNumber: woNumber,
        autoCreated: true,
        predictive: true,
        scheduledDate: input.scheduledDate as string || undefined,
        status: "open",
      })
      .returning({ id: workOrders.id })

    return { created: true, workOrderId: created.id, workOrderNumber: woNumber }
  },

  adjust_vendor_score: async (action) => {
    const input = action.inputData as Record<string, unknown>
    if (!action.entityId || input?.newScore === undefined) {
      throw new Error("Missing entityId or newScore")
    }

    await serviceDb
      .update(vendors)
      .set({
        performanceScore: String(input.newScore),
        updatedAt: new Date(),
      })
      .where(eq(vendors.id, action.entityId))

    return { updated: true, vendorId: action.entityId, newScore: input.newScore }
  },
}
