import { NextRequest, NextResponse } from "next/server"
import { requireTenantSession } from "@/lib/auth/tenant-session"
import { withTenantContext } from "@/lib/db/with-tenant-context"
import { serviceDb } from "@/lib/db"
import { notifications } from "@/lib/db/schema"
import { sql } from "drizzle-orm"

/**
 * GET /api/tenant/support-requests
 * List work orders (support requests) for the authenticated tenant.
 */
export async function GET() {
  let ctx
  try {
    ctx = await requireTenantSession()
  } catch (res) {
    return res as Response
  }

  try {
    const data = await withTenantContext(ctx.tenantId, async (tx) => {
      const rows = await tx.execute<{
        id: string
        work_order_number: string
        title: string
        description: string | null
        category: string | null
        priority: string | null
        status: string | null
        location: string | null
        created_at: string
        completed_at: string | null
        [key: string]: unknown
      }>(sql`
        SELECT
          id, work_order_number, title, description, category,
          priority, status, location, created_at, completed_at
        FROM work_orders
        WHERE tenant_id = current_setting('app.current_tenant_id')::uuid
        ORDER BY created_at DESC
        LIMIT 50
      `)

      return (Array.isArray(rows) ? rows : []).map((r) => ({
        id: r.id,
        workOrderNumber: r.work_order_number,
        title: r.title,
        description: r.description,
        category: r.category,
        priority: r.priority,
        status: r.status,
        location: r.location,
        createdAt: r.created_at,
        completedAt: r.completed_at,
      }))
    })

    return NextResponse.json({ success: true, data })
  } catch (err) {
    console.error("Tenant support requests GET error:", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

/**
 * POST /api/tenant/support-requests
 * Create a new support request (work order) from the tenant portal.
 */
export async function POST(request: NextRequest) {
  let ctx
  try {
    ctx = await requireTenantSession()
  } catch (res) {
    return res as Response
  }

  try {
    const body = await request.json()
    const { title, description, category, priority } = body as {
      title: string
      description: string
      category: string
      priority: string
    }

    if (!title || !category) {
      return NextResponse.json(
        { error: "Missing required fields: title, category" },
        { status: 400 },
      )
    }

    const data = await withTenantContext(ctx.tenantId, async (tx) => {
      // Get tenant's property from active lease
      const [lease] = await tx.execute<{
        property_id: string
        unit_number: string
        [key: string]: unknown
      }>(sql`
        SELECT property_id, unit_number
        FROM leases
        WHERE tenant_id = current_setting('app.current_tenant_id')::uuid
          AND status = 'active'
        ORDER BY end_date DESC
        LIMIT 1
      `)

      if (!lease) {
        throw new Error("NO_ACTIVE_LEASE")
      }

      // Generate work order number
      const seq = Date.now().toString().slice(-4)
      const year = new Date().getFullYear()
      const woNumber = `WO-${year}-${seq}`

      const [row] = await tx.execute<{
        id: string
        work_order_number: string
        [key: string]: unknown
      }>(sql`
        INSERT INTO work_orders (
          property_id, tenant_id, work_order_number,
          type, category, priority, title, description,
          location, status, metadata
        ) VALUES (
          ${lease.property_id}::uuid,
          current_setting('app.current_tenant_id')::uuid,
          ${woNumber},
          'repair',
          ${category},
          ${priority || "medium"},
          ${title},
          ${description || ""},
          ${"Unit " + lease.unit_number},
          'open',
          ${JSON.stringify({ source: "tenant_portal", submittedBy: ctx.email })}::jsonb
        )
        RETURNING id, work_order_number
      `)

      return row
    })

    // Create notification for admin users (fire-and-forget)
    serviceDb
      .insert(notifications)
      .values({
        recipientId: ctx.tenantId,
        recipientType: "user",
        type: "support_request",
        channel: "in_app",
        title: `New support request: ${title}`,
        content: `Tenant submitted a ${category} request (${priority || "medium"} priority): ${title}`,
        status: "sent",
        sentAt: new Date(),
        autoGenerated: true,
        metadata: { tenantId: ctx.tenantId, workOrderId: data.id },
      })
      .catch(() => {})

    return NextResponse.json(
      { success: true, data: { id: data.id, workOrderNumber: data.work_order_number } },
      { status: 201 },
    )
  } catch (err) {
    if (err instanceof Error && err.message === "NO_ACTIVE_LEASE") {
      return NextResponse.json(
        { error: "No active lease found. Cannot create support request." },
        { status: 400 },
      )
    }
    console.error("Tenant support request POST error:", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
