import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { serviceDb } from "@/lib/db"
import { notifications } from "@/lib/db/schema"
import { sql, eq, and, desc } from "drizzle-orm"

/**
 * GET /api/notifications
 * List notifications (admin-side). Filterable by recipientId, recipientType.
 */
export async function GET(request: NextRequest) {
  const session = await auth()
  if (!session?.user || session.user.role === "tenant") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const { searchParams } = request.nextUrl
  const recipientId = searchParams.get("recipientId")
  const recipientType = searchParams.get("recipientType")
  const limit = Math.min(parseInt(searchParams.get("limit") ?? "20", 10), 100)

  try {
    const conditions = []
    if (recipientId) conditions.push(eq(notifications.recipientId, recipientId))
    if (recipientType) conditions.push(eq(notifications.recipientType, recipientType))

    const rows = await serviceDb
      .select()
      .from(notifications)
      .where(conditions.length > 0 ? and(...conditions) : undefined)
      .orderBy(desc(notifications.createdAt))
      .limit(limit)

    return NextResponse.json({ success: true, data: rows })
  } catch (err) {
    console.error("Notifications GET error:", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

/**
 * POST /api/notifications
 * Create a notification (admin → tenant).
 */
export async function POST(request: NextRequest) {
  const session = await auth()
  if (!session?.user || session.user.role === "tenant") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  try {
    const body = await request.json()
    const { recipientId, type, title, content } = body as {
      recipientId: string
      type: string
      title: string
      content: string
    }

    if (!recipientId || !type || !title || !content) {
      return NextResponse.json(
        { error: "Missing required fields: recipientId, type, title, content" },
        { status: 400 },
      )
    }

    const [row] = await serviceDb
      .insert(notifications)
      .values({
        recipientId,
        recipientType: "tenant",
        type,
        channel: "in_app",
        title,
        content,
        status: "sent",
        sentAt: new Date(),
        autoGenerated: false,
        metadata: { sentBy: session.user.id, sentByName: session.user.name },
      })
      .returning()

    return NextResponse.json({ success: true, data: row }, { status: 201 })
  } catch (err) {
    console.error("Notifications POST error:", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
